### ISSUE TITLE
Undefined references when compiling with -DBUILD_SHARED_LIBS=On

### ISSUE THREAD

**Issue by mlohry** [LLNL/Umpire#699]
**Describe the bug**

Compilation for a shared library fails, but default static library succeeds.

**To Reproduce**

 cmake .. -DENABLE_CUDA=On -DBUILD_SHARED_LIBS=On 
make -j 12

**Expected behavior**

A shared libumpire.so library installation.

**Compilers & Libraries (please complete the following information):**
cmake configuration output:

-- The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using CMake version 3.16.3
-- BLT Source Directory: /home/mlohry/dev/Umpire/blt
-- BLT Version: 0.4.1
-- CMake Version: 3.16.3
-- CMake Executable: /usr/bin/cmake
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Git Support is ON
-- Git Executable: /usr/bin/git
-- Git Version: 2.25.1
-- MPI Support is OFF
-- OpenMP Support is OFF
-- CUDA Support is On
-- The CUDA compiler identification is NVIDIA 11.5.50
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.5") 
-- CUDA Version:       11.5
-- CUDA Toolkit Root Dir: /usr/local/cuda
-- CUDA Compiler:      /usr/local/cuda/bin/nvcc
-- CUDA Host Compiler: /usr/bin/c++
-- CUDA Include Path:  /usr/local/cuda/include
-- CUDA Libraries:     /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
-- CUDA Compile Flags: 
-- CUDA Link Flags:    -L/usr/local/cuda/lib64
-- CUDA Separable Compilation:  OFF
-- CUDA Link with NVCC:         
-- CUDA Implicit Link Libraries:   cudadevrt;cudart_static;rt;pthread;dl;stdc++;m;gcc_s;gcc;c;gcc_s;gcc
-- CUDA Implicit Link Directories: /usr/local/cuda/targets/x86_64-linux/lib/stubs;/usr/local/cuda/targets/x86_64-linux/lib;/usr/lib/gcc/x86_64-linux-gnu/9;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib
-- HIP Support is OFF
-- HCC Support is OFF
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Sphinx support is ON
-- Failed to locate Sphinx executable (missing: SPHINX_EXECUTABLE) 
-- Valgrind support is ON
-- Found Valgrind: /usr/bin/valgrind  
-- AStyle support is ON
-- Failed to locate AStyle executable (missing: ASTYLE_EXECUTABLE) 
-- ClangFormat support is ON
-- Found ClangFormat: /usr/bin/clang-format  
-- Uncrustify support is ON
-- Failed to locate Uncrustify executable (missing: UNCRUSTIFY_EXECUTABLE) 
-- Yapf support is ON
-- Failed to locate Yapf executable (missing: YAPF_EXECUTABLE) 
-- CMakeFormat support is ON
-- Failed to locate CMakeFormat executable (missing: CMAKEFORMAT_EXECUTABLE) 
-- Cppcheck support is ON
-- Failed to locate Cppcheck executable (missing: CPPCHECK_EXECUTABLE) 
-- ClangQuery support is ON
-- Failed to locate ClangQuery executable (missing: CLANGQUERY_EXECUTABLE) 
-- ClangTidy support is ON
-- Found ClangTidy: /usr/bin/clang-tidy  
-- C Compiler family is GNU
-- Adding optional BLT definitions and compiler flags
-- Setting CMAKE_CXX_EXTENSIONS to Off
-- Standard C++14 selected
-- Enabling all compiler warnings on all targets.
-- Fortran support disabled.
-- CMAKE_C_FLAGS flags are:    -Wall -Wextra 
-- CMAKE_CXX_FLAGS flags are:       -Wall -Wextra 
-- CMAKE_EXE_LINKER_FLAGS flags are:  
-- Google Test Support is ON
-- Google Mock Support is On
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Memcheck suppressions file: /home/mlohry/dev/Umpire/cmake/valgrind.supp
-- Setting C standard to 99
-- Checking for std::filesystem
-- Performing Test UMPIRE_ENABLE_FILESYSTEM
-- Performing Test UMPIRE_ENABLE_FILESYSTEM - Failed
-- std::filesystem NOT found, using POSIX
-- Host Shared Memory Disabled
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mlohry/dev/Umpire/build

**Additional context**

Compilation error:

Scanning dependencies of target tut_dynamic_pool_2
[ 82%] Building CXX object examples/tutorial/CMakeFiles/tut_dynamic_pool_2.dir/tut_dynamic_pool_2.cpp.o
[ 82%] Linking CUDA device code CMakeFiles/device_allocator_example.dir/cmake_device_link.o
nvlink error   : Undefined reference to '_ZN6umpire15DeviceAllocator8allocateEm' in 'CMakeFiles/device_allocator_example.dir/device-allocator.cpp.o'
nvlink error   : Undefined reference to '_ZN6umpire15DeviceAllocatorD1Ev' in 'CMakeFiles/device_allocator_example.dir/device-allocator.cpp.o'
nvlink error   : Undefined reference to '_ZN6umpire20get_device_allocatorEPKc' in 'CMakeFiles/device_allocator_example.dir/device-allocator.cpp.o'
nvlink error   : Undefined reference to '_ZN6umpire20get_device_allocatorEi' in 'CMakeFiles/device_allocator_example.dir/device-allocator.cpp.o'
make[2]: *** [examples/CMakeFiles/device_allocator_example.dir/build.make:87: examples/CMakeFiles/device_allocator_example.dir/cmake_device_link.o] Error 255
make[1]: *** [CMakeFiles/Makefile2:4828: examples/CMakeFiles/device_allocator_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by davidbeckingsale** [comment]
We've seen issues with shared libraries and CUDA in the past. Are you able to try with a newer version of CMake?

If not, a static build should work fine.

**Comment by davidbeckingsale** [comment]
This now works with CMake 3.20 - we have added a shared CUDA build to our CI.

**Comment by cameronrutherford** [comment]
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/umpire/package.py#L122 - does this mean that this line in the Umpire Spack package can be removed if people are using CMake >= 3.20?
